/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthenticatedDisparosIndexRouteImport } from './routes/_authenticated/disparos/index'
import { Route as AuthenticatedDisparosIdRouteImport } from './routes/_authenticated/disparos/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDisparosIndexRoute =
  AuthenticatedDisparosIndexRouteImport.update({
    id: '/disparos/',
    path: '/disparos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisparosIdRoute = AuthenticatedDisparosIdRouteImport.update({
  id: '/disparos/$id',
  path: '/disparos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disparos/$id': typeof AuthenticatedDisparosIdRoute
  '/disparos/': typeof AuthenticatedDisparosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disparos/$id': typeof AuthenticatedDisparosIdRoute
  '/disparos': typeof AuthenticatedDisparosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/_authenticated/disparos/$id': typeof AuthenticatedDisparosIdRoute
  '/_authenticated/disparos/': typeof AuthenticatedDisparosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/configuracoes' | '/disparos/$id' | '/disparos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/configuracoes' | '/disparos/$id' | '/disparos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/configuracoes'
    | '/_authenticated/disparos/$id'
    | '/_authenticated/disparos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/disparos/': {
      id: '/_authenticated/disparos/'
      path: '/disparos'
      fullPath: '/disparos/'
      preLoaderRoute: typeof AuthenticatedDisparosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disparos/$id': {
      id: '/_authenticated/disparos/$id'
      path: '/disparos/$id'
      fullPath: '/disparos/$id'
      preLoaderRoute: typeof AuthenticatedDisparosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDisparosIdRoute: typeof AuthenticatedDisparosIdRoute
  AuthenticatedDisparosIndexRoute: typeof AuthenticatedDisparosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDisparosIdRoute: AuthenticatedDisparosIdRoute,
  AuthenticatedDisparosIndexRoute: AuthenticatedDisparosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
