/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthenticatedCampanhasRouteImport } from './routes/_authenticated/campanhas'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedRevisaoRouteImport } from './routes/_authenticated/revisao'
import { Route as RTokenRouteImport } from './routes/r/$token'
import { Route as AuthenticatedDisparosIndexRouteImport } from './routes/_authenticated/disparos/index'
import { Route as AuthenticatedDisparosIdRouteImport } from './routes/_authenticated/disparos/$id'
import { Route as ApiPublicCronDispatchRouteImport } from './routes/api/public/cron/dispatch'
import { Route as ApiPublicHooksBrevoRouteImport } from './routes/api/public/hooks/brevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampanhasRoute = AuthenticatedCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisaoRoute = AuthenticatedRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDisparosIndexRoute =
  AuthenticatedDisparosIndexRouteImport.update({
    id: '/disparos/',
    path: '/disparos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisparosIdRoute = AuthenticatedDisparosIdRouteImport.update({
  id: '/disparos/$id',
  path: '/disparos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCronDispatchRoute = ApiPublicCronDispatchRouteImport.update({
  id: '/api/public/cron/dispatch',
  path: '/api/public/cron/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBrevoRoute = ApiPublicHooksBrevoRouteImport.update({
  id: '/api/public/hooks/brevo',
  path: '/api/public/hooks/brevo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/links': typeof AuthenticatedLinksRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/r/$token': typeof RTokenRoute
  '/disparos/$id': typeof AuthenticatedDisparosIdRoute
  '/disparos/': typeof AuthenticatedDisparosIndexRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
  '/api/public/hooks/brevo': typeof ApiPublicHooksBrevoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/campanhas': typeof AuthenticatedCampanhasRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/links': typeof AuthenticatedLinksRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/r/$token': typeof RTokenRoute
  '/disparos/$id': typeof AuthenticatedDisparosIdRoute
  '/disparos': typeof AuthenticatedDisparosIndexRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
  '/api/public/hooks/brevo': typeof ApiPublicHooksBrevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/_authenticated/campanhas': typeof AuthenticatedCampanhasRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/revisao': typeof AuthenticatedRevisaoRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/disparos/$id': typeof AuthenticatedDisparosIdRoute
  '/_authenticated/disparos/': typeof AuthenticatedDisparosIndexRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
  '/api/public/hooks/brevo': typeof ApiPublicHooksBrevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/campanhas'
    | '/contatos'
    | '/links'
    | '/revisao'
    | '/r/$token'
    | '/disparos/$id'
    | '/disparos/'
    | '/api/public/cron/dispatch'
    | '/api/public/hooks/brevo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/campanhas'
    | '/contatos'
    | '/links'
    | '/revisao'
    | '/r/$token'
    | '/disparos/$id'
    | '/disparos'
    | '/api/public/cron/dispatch'
    | '/api/public/hooks/brevo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/configuracoes'
    | '/_authenticated/campanhas'
    | '/_authenticated/contatos'
    | '/_authenticated/links'
    | '/_authenticated/revisao'
    | '/r/$token'
    | '/_authenticated/disparos/$id'
    | '/_authenticated/disparos/'
    | '/api/public/cron/dispatch'
    | '/api/public/hooks/brevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicCronDispatchRoute: typeof ApiPublicCronDispatchRoute
  ApiPublicHooksBrevoRoute: typeof ApiPublicHooksBrevoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campanhas': {
      id: '/_authenticated/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AuthenticatedCampanhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisao': {
      id: '/_authenticated/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof AuthenticatedRevisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/disparos/': {
      id: '/_authenticated/disparos/'
      path: '/disparos'
      fullPath: '/disparos/'
      preLoaderRoute: typeof AuthenticatedDisparosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disparos/$id': {
      id: '/_authenticated/disparos/$id'
      path: '/disparos/$id'
      fullPath: '/disparos/$id'
      preLoaderRoute: typeof AuthenticatedDisparosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/dispatch': {
      id: '/api/public/cron/dispatch'
      path: '/api/public/cron/dispatch'
      fullPath: '/api/public/cron/dispatch'
      preLoaderRoute: typeof ApiPublicCronDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/brevo': {
      id: '/api/public/hooks/brevo'
      path: '/api/public/hooks/brevo'
      fullPath: '/api/public/hooks/brevo'
      preLoaderRoute: typeof ApiPublicHooksBrevoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampanhasRoute: typeof AuthenticatedCampanhasRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedRevisaoRoute: typeof AuthenticatedRevisaoRoute
  AuthenticatedDisparosIdRoute: typeof AuthenticatedDisparosIdRoute
  AuthenticatedDisparosIndexRoute: typeof AuthenticatedDisparosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampanhasRoute: AuthenticatedCampanhasRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedRevisaoRoute: AuthenticatedRevisaoRoute,
  AuthenticatedDisparosIdRoute: AuthenticatedDisparosIdRoute,
  AuthenticatedDisparosIndexRoute: AuthenticatedDisparosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicCronDispatchRoute: ApiPublicCronDispatchRoute,
  ApiPublicHooksBrevoRoute: ApiPublicHooksBrevoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
