// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    // Supabase services can briefly disagree about the current time just after
    // a session is issued. Retrying here also covers PostgREST queries, whereas
    // retrying only auth.getClaims leaves the first database request vulnerable.
    const retryDelays = [1_000, 2_000, 4_000, 8_000];
    for (let attempt = 0; ; attempt += 1) {
      const requestInput =
        typeof Request !== 'undefined' && input instanceof Request ? input.clone() : input;
      const response = await fetch(requestInput, { ...init, headers });
      const canRetry = attempt < retryDelays.length && response.status >= 400;
      if (!canRetry) return response;

      const body = await response.clone().text();
      if (!/jwt issued at future/i.test(body)) return response;

      await new Promise((resolve) => setTimeout(resolve, retryDelays[attempt]));
    }
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env['SUPABASE_URL'];
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    // A token whose `iat` is ahead of this server's clock is rejected by
    // PostgREST with "JWT issued at future". Wait out the skew before querying.
    try {
      const payload = JSON.parse(
        Buffer.from(token.split('.')[1]!, 'base64url').toString('utf8'),
      ) as { iat?: number };
      const skewMs = typeof payload.iat === 'number' ? payload.iat * 1000 - Date.now() : 0;
      if (skewMs > 0) {
        await new Promise((resolve) => setTimeout(resolve, Math.min(skewMs + 1000, 20_000)));
      }
    } catch {
      // malformed payload: let the normal validation below reject it
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    let { data, error } = await supabase.auth.getClaims(token);

    // Small clock skew between the app server and the auth server can make a
    // freshly issued token look like it comes from the future. Wait briefly and retry once.
    if (error && /issued at future/i.test(error.message ?? '')) {
      await new Promise((resolve) => setTimeout(resolve, 2000));
      ({ data, error } = await supabase.auth.getClaims(token));
    }

    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
