// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

async function getUsableAccessToken(): Promise<string | undefined> {
  const { data } = await supabase.auth.getSession();
  return data.session?.access_token;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const token = await getUsableAccessToken();

    // Never refresh specifically because PostgREST says the JWT is from the
    // future. A refreshed token gets a newer iat and perpetuates the clock-skew
    // loop. The server retries this same token until its iat is accepted.
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
